### PR TITLE
Improved results and made it responsive

### PR DESCRIPTION
**Pull request by sarthakChauhan12**
This pull request solve issue #13

### CODE REVIEW

**Comment by abhizaik** [comment]
Hi @sarthakChauhan12 , the result page looks better in both mobile and desktop views now. However, I noticed a few issues and improvements that could be made:

- The footer looks small and disorganized in both views (HTML for the footer is in `base.html`).
- In the desktop view, it would look better if the title and description were a bit larger to match the size of the result section.

Could you address these points in your next commit so that we can merge the code?

Thanks!

**Comment by sarthakChauhan12** [comment]
Sure. Assign this issue to me. I'll work on these things and make these changes.

**Comment by abhizaik** [comment]
Sure, please comment on the issue that you're working on the issue so that I can add you to the list.

**Comment by sarthakChauhan12** [comment]
I made the changes and made new PR. Please check and verify.

**Comment by abhizaik** [comment]
Hi @sarthakChauhan12,

I had checked the preview and everything looked good, so I merged the code. However, after the merge, the production version looks kinda bad now. There haven't been any other commits in between.

Could you please check what's the issue? Make sure to pull the latest changes from the main branch first.

**Comment by abhizaik** [comment]
Hi @sarthakChauhan12 nerver mind, it was a cache issue, it's working fine on prod also now. Thanks for the contribution!

**Pull request merged**
